apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sip2ai.fullname" . }}
  labels:
    {{- include "sip2ai.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
