{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sip2ai.fullname" . }}
  labels:
    {{- include "sip2ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.openai }}
  openai: {{ .Values.secrets.openai | quote }}
  {{- end }}
  {{- if .Values.secrets.deepgram }}
  deepgram: {{ .Values.secrets.deepgram | quote }}
  {{- end }}
  {{- if .Values.secrets.gemini }}
  gemini: {{ .Values.secrets.gemini | quote }}
  {{- end }}
{{- end }}
